---
- hosts: all
  vars: 
   packagename: topbeat_1.0.0-rc1_amd64.deb
   es_host: 127.0.0.1
   es_port: 9200
   period: 5
   start: true
   autostart: false

  tasks:
  - name: download topbeat deb package
    get_url: url=https://download.elasticsearch.org/beats/topbeat/{{ packagename }} dest=/tmp/{{ packagename }}

  - name: install topbeat deb package
    apt: deb=/tmp/{{ packagename }}

  - name: configure topbeat interval
    lineinfile: 'dest=/etc/topbeat/topbeat.yml "regexp=^ period:.*" line=" period: {{ period }}"'

  - name: configure topbeat elasticsearch
    lineinfile: 'dest=/etc/topbeat/topbeat.yml regexp="hosts:.*" line="    hosts: [\"{{ es_host }}:{{ es_port }}\"]"'

  - name: ensure curl is installed
    apt: package=curl state=present update_cache=yes

  - name: insert template into elasticsearch
    shell: 'curl -s {{ es_host }}:{{ es_port }}/_template/topbeat -d @/etc/topbeat/topbeat.template.json '

  - name: start topbeat service
    service: name=topbeat state=started
    when: start
  
  - name: add topbeat to autostart
    shell: update-rc.d topbeat defaults 95 10
    when: autostart
